version: "3"
services:
  finpro:
    container_name: finpro
    build:
      context: .
      dockerfile: Dockerfile
    image: finpro:latest
    restart: unless-stopped
    env_file: .env
    # working_dir: /opt
    environment:
      NODE_ENV: production
  
    ports:
      - "8000:8000"
      - "3000:3000"
    networks:
      - finpro
      - public
    depends_on:
      - finproDB


  finproDB:
    container_name: finproDB
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      # - ./data:/var/lib/mysql
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    ports:
      - "3930:3306"
    networks:
      - finpro

networks:
  finpro:
    name: finpro
    driver: bridge
  public:
    external: true
      
# volumes:
#   finpro:
#     name: finpro